baseurl = "https://me.auruchan.web.id/"
languageCode = "id-ind"
theme = "hello-friend"
paginate = 5
googleAnalytics = "UA-68615481-6"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # Show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.en]
    title = "Kesandung Blog ~.~"
    subtitle = "Cicit Cuit Rengga Prakoso Nugroho"
    keywords = "vzrenggamani, Rengga Nugroho, Rengga Prakoso Nugroho"
    copyright = "vzrenggamani"
    menuMore = "Show more"
    #writtenBy = "Rengga Prakoso Nugroho"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "Rengga Prakoso Nugroho"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "portofolio"
        name = "Portofolio"
        url = "https://rengga.auruchan.web.id"
      [[languages.en.menu.main]]
        identifier = "archive"
        name = "Archive"
        url = "/archive"
