name: Blog Deployment
on:
  push:
    branches: master
jobs:
  BuildDeploy:
    name: Blog Build and Deployment
    runs-on: [ubuntu-18.04]
    env:
     BLOGTOKEN: ${{ secrets.BLOG_TOKEN }}
     ci: true
    steps:
       - uses: peaceiris/actions-hugo@v2
         with:
          hugo-version: 'latest'
       - uses: actions/setup-node@v1
         with:
          node-version: '12.x'

       - run: echo == 
       - run: dir
