name: Blog Deployment
on: [push]
jobs:
  BuildDeploy:
    name: Blog Build and Deployment
    runs-on: [ubuntu-18.04]
    steps:
       - uses: peaceiris/actions-hugo@v2
         with:
          hugo-version: 'latest'
       - uses: actions/setup-node@v1
         with:
          node-version: '12.x'
       - name: Install Dependencies
         run: npm i -g npm@latest
              npm install workbox-cli --global
              npm install netlify-cli -g
              netlify
       - name: Deployment
         env:
           BLOGTOKEN: ${{ secrets.BLOG_TOKEN }}
         run: hugo build --minify &&
              workbox generateSW .\workbox-config.js &&
              netlify deploy --site renggablog --auth $BLOGTOKEN --prod --dir=public
