name: Blog Deployment | Firebase Hosting
on:
  push:
    branches:  # RUn only in master's branch commit
    - master

jobs:
  
  build:
    name: Blog Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout  # Checkout repository latest commit
        uses: actions/checkout@v2.0.0

      - name: Submodule Checkout # Gte the theme repository
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
        
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: npm install workbox-cli -g
       
      - name: Build Sites
        run: hugo --minify  # Build the sites with minified version
       
      - name: Generate Service Worker
        run: workbox injectManifest workbox-config.js   # Inject cache manifest sw to production Service Worker
      
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master    # Upload built sites to GitHub actions artifact
        with:
          name: public
          path: public
  deploy:
    name: Deploy to Firebase
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo   # Checkout and download the sites artifact previously created
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:catatan   # Deploy to FIrebase Hosting : "Catatan" Sites
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Get the token from the GitHub Repos Secrets
