name: Blog Deployment | Firebase Hosting
on:
  push:
    branches: 
    - master

jobs:
  
  build:
    name: Blog Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.0.0

      - name: Submodule Checkout
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
        
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: npm install workbox-cli -g
       
      - name: Build Sites
        run: hugo --minify 
       
      - name: Generate Service Worker
        run: workbox generateSW
      
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: .
  deploy:
    name: Deploy to Firebase
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:catatan
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
